apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 2 # Runs two instances of your app for high availability
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        # This image URI will be dynamically updated by Jenkins later
        image: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/devops-fastapi-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer # Provisions an AWS Network Load Balancer
  selector:
    app: fastapi
  ports:
  - port: 80
    targetPort: 8000
